name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.3'
          cache: yarn

      - name: Install Package
        run: |
          npm install yarn
          yarn install

      - name: Prettier
        run: yarn prettier

      - name: Lint
        run: yarn lint

      - name: Build
        run: |
          yarn build
