name: Deploy

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.3'
          cache: yarn

      - name: Build
        run: |
          yarn install
          yarn build
          tar czf dist.tar.gz dist

      - name: Deploy
        run: |
          ssh_identifier="identifier"
          echo "${{ secrets.DEPLOY_SERVER_IDENTIFIER }}" > ${ssh_identifier}
          chmod 600 ${ssh_identifier}
          scp -P ${{ secrets.DEPLOY_SERVER_PORT }} \
              -i ${ssh_identifier} \
              -o StrictHostKeyChecking=no \
              dist.tar.gz deploy.sh ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/.
          ssh ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_HOST }} \
              -p ${{ secrets.DEPLOY_SERVER_PORT }} \
              -i ${ssh_identifier} \
              -o StrictHostKeyChecking=no \
              bash ${{ secrets.DEPLOY_PATH }}/deploy.sh
          rm ${ssh_identifier}
